/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.5 */

#ifndef PB_HEDERA_PROTO_CONTRACT_CALL_PB_H_INCLUDED
#define PB_HEDERA_PROTO_CONTRACT_CALL_PB_H_INCLUDED
#include <pb.h>
#include "proto/basic_types.pb.h"

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Struct definitions */
typedef PB_BYTES_ARRAY_T(512) Hedera_ContractCallTransactionBody_functionParameters_t;
/* *
 Call a function of a given smart contract, providing function parameter
 inputs as needed.

 Resource ("gas") charges SHALL include all relevant fees incurred by the
 contract execution, including any storage required.<br/>
 The total transaction fee SHALL incorporate all of the "gas" actually
 consumed as well as the standard fees for transaction handling, data
 transfers, signature verification, etc...<br/>
 The response SHALL contain the output returned by the function call.

 ### Block Stream Effects
 A `CallContractOutput` message SHALL be emitted for each transaction. */
typedef struct _Hedera_ContractCallTransactionBody { 
    /* *
 The ID of a smart contract to call. */
    bool has_contractID;
    Hedera_ContractID contractID; 
    /* Gas is defined as int64 in upstream proto (we could have negative gas); the app rejects negative values
 Reference: https://github.com/hashgraph/hedera-protobufs/blob/8c27786cec93abab974309074feaef9b48a695b7/services/contract_call.proto#L70 */
    int64_t gas; 
    /* *
 An amount of tinybar sent via this contract call.
 <p>
 If this is non-zero, the function MUST be `payable`. */
    int64_t amount; 
    Hedera_ContractCallTransactionBody_functionParameters_t functionParameters; 
} Hedera_ContractCallTransactionBody;


#ifdef __cplusplus
extern "C" {
#endif

/* Initializer values for message structs */
#define Hedera_ContractCallTransactionBody_init_default {false, Hedera_ContractID_init_default, 0, 0, {0, {0}}}
#define Hedera_ContractCallTransactionBody_init_zero {false, Hedera_ContractID_init_zero, 0, 0, {0, {0}}}

/* Field tags (for use in manual encoding/decoding) */
#define Hedera_ContractCallTransactionBody_contractID_tag 1
#define Hedera_ContractCallTransactionBody_gas_tag 2
#define Hedera_ContractCallTransactionBody_amount_tag 3
#define Hedera_ContractCallTransactionBody_functionParameters_tag 4

/* Struct field encoding specification for nanopb */
#define Hedera_ContractCallTransactionBody_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, MESSAGE,  contractID,        1) \
X(a, STATIC,   SINGULAR, INT64,    gas,               2) \
X(a, STATIC,   SINGULAR, INT64,    amount,            3) \
X(a, STATIC,   SINGULAR, BYTES,    functionParameters,   4)
#define Hedera_ContractCallTransactionBody_CALLBACK NULL
#define Hedera_ContractCallTransactionBody_DEFAULT NULL
#define Hedera_ContractCallTransactionBody_contractID_MSGTYPE Hedera_ContractID

extern const pb_msgdesc_t Hedera_ContractCallTransactionBody_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define Hedera_ContractCallTransactionBody_fields &Hedera_ContractCallTransactionBody_msg

/* Maximum encoded size of messages (where known) */
#define Hedera_ContractCallTransactionBody_size  583

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
